# TODO: Fokus auf zusammenspiel zwischen json-server und react-app legen, anschliessend auf backend
version: "3.8"
services:
  smash-grade-frontend:
    image: smashgrade-react:latest
    container_name: smash-grade-frontend
    ports:
      - "80:80"
    networks:
      - smash-grade-network
    depends_on:
        - json-server
  json-server:
    image: ghcr.io/smashgrade/smashgrade-app/json-server:latest
    container_name: json-server
    ports:
      - "3000:3000"
    networks:
      - smash-grade-network

networks:
  smash-grade-network:
    driver: bridge
