version: "3.8"
services:
  smash-grade-frontend:
    image: ghcr.io/smashgrade/react-app:dev-latest
    container_name: smash-grade-frontend
    ports:
      - "80:80"
    networks:
      - smash-grade-network
    depends_on:
        - json-server

  json-server:
    image: ghcr.io/smashgrade/json-server:dev-latest
    container_name: json-server
    ports:
      - "3000:3000"
    networks:
      - smash-grade-network

  smash-grade-backend:
      image: ghcr.io/smashgrade/backend:dev
      container_name: smash-grade-backend
      ports:
        - "9191:9000"
      environment:
        - ENV=dev
        - API_MOCK_DATA=true
        - API_LOG_LEVEL=debug
      networks:
        - smash-grade-network
      volumes:
        - ./api/config.yaml:/app/config.yaml

networks:
  smash-grade-network:
    driver: bridge

