name: Build and deploy React App

on:
  pull_request:
    types: [ opened, synchronize, closed ]
    branches:
      - dev
  push:
    branches:
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment:
      name: ${{ github.event_name == 'pull_request' && format('smashgrade-app-pr-preview-{0}', github.event.pull_request.number) || 'Production' }}
      url: ${{ github.event_name == 'pull_request' && format('https://salmon-meadow-0f230d803-{0}.westeurope.3.azurestaticapps.net', github.event.pull_request.number) || 'https://www.smashgrade.ch' }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Create .env.pullrequest file
        if: github.event_name == 'pull_request'
        run: |
          echo "VITE_BACKEND_API_URL=https://jsonserver-api-preview-pr-${{ github.event.pull_request.number}}.azurewebsites.net" > .env.pullrequest 
          echo "VITE_AUTH_REDIRECT_URL=https://salmon-meadow-0f230d803-${{ github.event.pull_request.number}}.westeurope.3.azurestaticapps.net" > .env.pullrequest 
          cat .env.pullrequest 

      - name: Remove NPM prepare script
        run: npm pkg delete scripts.prepare

      - name: Build And Deploy to Azure Static Web app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_MEADOW_0F230D803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_build_command: ${{ github.event_name == 'pull_request' && 'npm run build:pr' || 'npm run build' }}
          skip_api_build: true
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          output_location: "dist" # Built app content directory - optional


      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Current Redirect URIs
        uses: Azure/cli@v1
        with:
          inlineScript: |
            appRegId="fcb522a3-6a27-4c84-b4fb-3871ef2a7986"
            redirectType="spa"
            redirectUrl="https://salmon-meadow-0f230d803-${{ github.event.pull_request.number}}.westeurope.3.azurestaticapps.net"
            graphUrl="https://graph.microsoft.com/v1.0/applications/$appRegId"
            result=$(az rest --method GET --uri "$graphUrl" --headers "Content-Type=application/json")
            # Extract redirectUris from the result using jq (assuming jq is installed)
            existingRedirectUris=$(echo "$result" | jq -r '.spa.redirectUris[]')
            # Add the new redirectUrl to the existing redirectUris
            updatedRedirectUris=("$existingRedirectUris" "$redirectUrl")
            # Using a heredoc for the payload
            read -r -d '' payload <<EOF
            {
              "spa": {
                "redirectUris": $(printf '%s\n' "${updatedRedirectUris[@]}" | jq -R . | jq -s .)
              }
            }
            EOF
            echo "$payload"
            az rest --method PATCH --uri "$graphUrl" --headers "Content-Type=application/json" --body "$payload"

  add-azure-redirect-uri:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Current Redirect URIs
        uses: Azure/cli@v1
        with:
          inlineScript: |
            appRegId="fcb522a3-6a27-4c84-b4fb-3871ef2a7986"
            redirectType="spa"
            redirectUrl="https://salmon-meadow-0f230d803-${{ github.event.pull_request.number}}.westeurope.3.azurestaticapps.net"
            graphUrl="https://graph.microsoft.com/v1.0/applications/$appRegId"
            result=$(az rest --method GET --uri "$graphUrl" --headers "Content-Type=application/json")
            # Extract redirectUris from the result using jq (assuming jq is installed)
            existingRedirectUris=$(echo "$result" | jq -r '.spa.redirectUris[]')
            # Add the new redirectUrl to the existing redirectUris
            updatedRedirectUris=("$existingRedirectUris" "$redirectUrl")
            # Using a heredoc for the payload
            read -r -d '' payload <<EOF
            {
              "spa": {
                "redirectUris": $(printf '%s\n' "${updatedRedirectUris[@]}" | jq -R . | jq -s .)
              }
            }
            EOF
            az rest --method PATCH --uri "$graphUrl" --headers "Content-Type=application/json" --body "$payload"


  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_MEADOW_0F230D803 }}
          action: "close"

      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.WORKFLOW_APP_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}

      - name: 🗑 Delete deployment environment
        uses: strumwolf/delete-deployment-environment@v2.2.3
        with:
          # Use a JWT created with your GitHub App's private key
          token: ${{ steps.generate_token.outputs.token }}
          environment: smashgrade-app-pr-preview-${{ github.event.pull_request.number}}
