# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - json-server-api

on:
  push:
    branches:
      - "#5-containeraize-react-app"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: ./api

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install-clean
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip json-server.zip ./* -r

      - name: output directory
        run: |
            pwd
            ls -la

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: json-server
          path: ./api/json-server.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: json-server

      - name: Unzip artifact for deployment
        run: unzip json-server.zip

      - name: output directory
        run: |
          pwd
          ls -la

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jsonserver-api'
          slot-name: 'production'
          package: .