name: Docker Image CI

# Create a new Docker image on every push to dev or on tag creation
on:
  push:
    branches:
      - dev
    tags:
      - '*'

jobs:
  build-tagged-docker-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: ghcr.io/smashgrade/react-app
            buildContext: .
          - dockerfile: ./api/Dockerfile
            image: ghcr.io/smashgrade/json-server
            buildContext: ./api
    permissions:
      packages: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to the GHCR Container registry
        uses: docker/login-action@v3
        with:
            registry: https://ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images with given tag
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ matrix.image }}:${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'dev-latest' }}
          context: ${{ matrix.buildContext }}
          file: ${{ matrix.dockerfile }}