name: Set closed date on issues

on:
  issues:
    types: [ closed ]

permissions:
  issues: write
  repository-projects: write

jobs:
  update-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date to env variable
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.WORKFLOW_APP_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}

      - name: Update closed date
        id: update_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          organization: SmashGrade
          project_number: 1
          content_id: ${{ github.event.issue.node_id }}
          field: Closed Date
          value: ${{ steps.date.outputs.date }}


