name: Set closed date on issues

on:
  issues:
    types: [closed]

permissions:
  issues: write
  repository-projects: write

jobs:
  update-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          DATE: ${{ steps.date.outputs.date }}
        run: |
          echo "current date $DATE"
          echo "$GITHUB_CONTEXT"

      - name: Update closed date
        id: update_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          organization: SmashGrade
          project_number: 1
          content_id: ${{ github.event.issue.id }}
          field: Closed Date
          value: ${{ steps.date.outputs.date }}


