#!/bin/bash


appRegId="fcb522a3-6a27-4c84-b4fb-3871ef2a7986"

redirectUrl="https://www.post.com/oauth2/callback"
graphUrl="https://graph.microsoft.com/v1.0/applications/$appRegId"

result=$(az rest --method GET --uri "$graphUrl" --headers "Content-Type=application/json")
echo "$result"
# Extract redirectUris from the result using jq (assuming jq is installed)
existingRedirectUris=$(echo "$result" | jq -r '.spa.redirectUris[]')

# Print the existing redirectUris
echo "Existing redirectUris: $existingRedirectUris"

# Add the new redirectUrl to the existing redirectUris
updatedRedirectUris=("$existingRedirectUris" "$redirectUrl")

# Using a heredoc for the payload
read -r -d '' payload <<EOF
{
  "spa": {
    "redirectUris": $(printf '%s\n' "${updatedRedirectUris[@]}" | jq -R . | jq -s .)
  }
}
EOF

echo "Payload: $payload"

az rest --method PATCH --uri "$graphUrl" --headers "Content-Type=application/json" --body "$payload"
